name: Publish nuget package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-api-key-source: https://api.nuget.org/v3/index.json
        nuget-version: '5.x'
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Create nuget package
      run: nuget pack TgBotFramework.Template.nuspec -NoDefaultExcludes
      
    - name: Push nuget package
      run: nuget push TgBotFramework.Template.nupkg -Source https://api.nuget.org/v3/index.json
